test global CI/CD

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -51,19 +51,19 @@ jobs:
 
       - name: attente du build
         run: |
-          timeout 60s bash -c 'until curl -s http://localhost:8080/api/health; do sleep 2; done' || (docker compose -f docker-compose.ci.yaml logs && exit 1)
+          timeout 60s bash -c 'until curl -s http://localhost:8080/api/test; do sleep 2; done' || (docker compose -f docker-compose.ci.yaml logs && exit 1)
 
       #- name: Exécuter les tests d'intégration
       #  run: python3 tests/testCompil.py
       #  env:
       #    TEST_SERVER_URL: http://localhost:8080
 
-      - name: Afficher les logs en cas d'échec
-        if: failure()
-        run: |
-          docker compose -f docker-compose.ci.yaml ps
-          docker compose -f docker-compose.ci.yaml logs pythonserver
-          docker compose -f docker-compose.ci.yaml logs db
+      #- name: Afficher les logs en cas d'échec
+      #  if: failure()
+      #  run: |
+      #    docker compose -f docker-compose.ci.yaml ps
+      #    docker compose -f docker-compose.ci.yaml logs pythonserver
+      #    docker compose -f docker-compose.ci.yaml logs db
 
       - name: Clean up
         if: always()
